# This file was generated by GoReleaser. DO NOT EDIT.
cask "fleetbox" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "e8484048e726e6c3d424eb74e1c64beb83eb9f3ad54d9392c64b6ef11c45507d"
      url "https://github.com/pilat/fleetbox/releases/download/v#{version}/fleetbox_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/pilat/fleetbox/"
    end
  end

  on_linux do
    on_intel do
      sha256 "0dd3562d20c312790ab70d32009302f42c33a1891143521d87563bf69c684dcc"
      url "https://github.com/pilat/fleetbox/releases/download/v#{version}/fleetbox_#{version}_linux_amd64.tar.gz",
        verified: "github.com/pilat/fleetbox/"
    end
    on_arm do
      sha256 "e6acb3ad706eb6176785beae2b27535e33cb0a315c943cfc96ea218c0bf55848"
      url "https://github.com/pilat/fleetbox/releases/download/v#{version}/fleetbox_#{version}_linux_arm64.tar.gz",
        verified: "github.com/pilat/fleetbox/"
    end
  end

  name "fleetbox"
  desc "Linux VMs as Go test fixtures, on macOS and Linux behind one backend-neutral API"
  homepage "https://github.com/pilat/fleetbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fleetbox"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fleetbox"]
    end
  end
  generate_completions_from_executable "fleetbox", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

  caveats <<~EOS
    fleetbox boots real Linux VMs. The first `fleetbox up` downloads, checksum-pinned
    into ~/.fleetbox/, a small signed fleetbox-helper (macOS, Apple Silicon, 26+).
    Intel Macs are not supported.
  EOS
end
