# This file was generated by GoReleaser. DO NOT EDIT.
cask "fleetbox" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "5b2e922cc1771fd901f226a222e229e8803612de5ea30c5afbaf554aa8ad9028"
      url "https://github.com/pilat/fleetbox/releases/download/v#{version}/fleetbox_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/pilat/fleetbox/"
    end
  end

  on_linux do
    on_intel do
      sha256 "5d1c74f4886f2fb6e5dc5c0c8626b6736dd878977ba27918671c9daa6004bce7"
      url "https://github.com/pilat/fleetbox/releases/download/v#{version}/fleetbox_#{version}_linux_amd64.tar.gz",
        verified: "github.com/pilat/fleetbox/"
    end
    on_arm do
      sha256 "f0ff3f5059810badecf17ed9b4f4a93aab4961def60dfdf432954a71a1d7cbb3"
      url "https://github.com/pilat/fleetbox/releases/download/v#{version}/fleetbox_#{version}_linux_arm64.tar.gz",
        verified: "github.com/pilat/fleetbox/"
    end
  end

  name "fleetbox"
  desc "Linux VMs as Go test fixtures, on macOS and Linux behind one backend-neutral API"
  homepage "https://github.com/pilat/fleetbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fleetbox"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fleetbox"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    fleetbox boots real Linux VMs. The first `fleetbox up` downloads, checksum-pinned
    into ~/.fleetbox/, a small signed fleetbox-helper (macOS, Apple Silicon, 26+).
    Intel Macs are not supported.
  EOS
end
