# This file was generated by GoReleaser. DO NOT EDIT.
cask "fleetbox" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "4122341f67fde4ae42726dbb4000d4f8205382f12b1c96d418b4f6af38ccd092"
      url "https://github.com/pilat/fleetbox/releases/download/v#{version}/fleetbox_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/pilat/fleetbox/"
    end
  end

  on_linux do
    on_intel do
      sha256 "b86defc0a44bf272e856e5cd5197b3f0ae0ab2d4c42b8378df02890e1cfb86cb"
      url "https://github.com/pilat/fleetbox/releases/download/v#{version}/fleetbox_#{version}_linux_amd64.tar.gz",
        verified: "github.com/pilat/fleetbox/"
    end
    on_arm do
      sha256 "bc5cbbc4169824edc05692c725279b030dc420d83bfd5e9881c573d51d4d2b11"
      url "https://github.com/pilat/fleetbox/releases/download/v#{version}/fleetbox_#{version}_linux_arm64.tar.gz",
        verified: "github.com/pilat/fleetbox/"
    end
  end

  name "fleetbox"
  desc "Linux VMs as Go test fixtures, on macOS and Linux behind one backend-neutral API"
  homepage "https://github.com/pilat/fleetbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fleetbox"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fleetbox"]
    end
  end
  generate_completions_from_executable "fleetbox", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

  caveats <<~EOS
    fleetbox boots real Linux VMs. The first `fleetbox up` downloads, checksum-pinned
    into ~/.fleetbox/, a small signed fleetbox-helper (macOS, Apple Silicon, 26+).
    Intel Macs are not supported.
  EOS
end
